### ISSUE TITLE
Charts does display more datapoints that i configured

### ISSUE THREAD

**Issue by nicox** [Zefau/ioBroker.jarvis#384]
**Prerequisites**
- [1.0.9 ] Are you on the latest stable or latest beta of jarvis?
- [x] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: ... 1.0.9
- Please provide your `Support-ID` (in jarvis via Settings -> Help): ...  i can not find tha Help, i am sorry.

**Describe the bug**
I have 2 charts which should display the same devices but different Datapoint but both charts will display all datapoints.

**Expected behavior**
1 Chart should display the Temperature and one the Humidity.

**Screenshots**
![image](https://user-images.githubusercontent.com/1413618/100514181-d8e74500-3172-11eb-9e19-f11df89410d4.png)

Config:
```
{
   "82acd93a-1df1-4e45-8922-7b8c2b196eb0":{
      "id":"82acd93a-1df1-4e45-8922-7b8c2b196eb0",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0003f7a5a9.state"
            },
            "action":"",
            "display":{
               "true":"offen",
               "false":"geschlossen"
            },
            "label":"Fenster"
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606417253742,
         "_updated":1606520786555
      },
      "name":"Schlafzimmer",
      "function":"window"
   },
   "bd58a233-d20f-4d94-8960-c908a4a121f1":{
      "id":"bd58a233-d20f-4d94-8960-c908a4a121f1",
      "states":{
         "Luftfeuchtigkeit":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000465ba63.humidity"
            },
            "unit":"%"
         },
         "temp":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000465ba63.temperature"
            },
            "unit":"°C"
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606418139258,
         "_updated":1606418341009
      },
      "name":"Schlafzimmer",
      "function":"other"
   },
   "d16272d6-a2c7-44e0-91ed-950bec90a957":{
      "id":"d16272d6-a2c7-44e0-91ed-950bec90a957",
      "states":{
         "Luftfeuchtigkeit":{
            "state":{
               "node":"mihome.0.devices.weather_v1_158d0002f81ae7.humidity"
            },
            "unit":"%"
         },
         "Temp":{
            "state":{
               "node":"mihome.0.devices.weather_v1_158d0002f81ae7.temperature"
            },
            "unit":"°C"
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606420138026,
         "_updated":1606420667908
      },
      "name":"Badezimmer ",
      "function":"other"
   },
   "b8be8400-e0dc-4451-9df7-61e68b32cfae":{
      "id":"b8be8400-e0dc-4451-9df7-61e68b32cfae",
      "states":{
         "Luftfeuchtigkeit":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000358089e.humidity"
            },
            "unit":"%"
         },
         "Temp":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000358089e.temperature"
            },
            "unit":"°C"
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606420529358,
         "_updated":1606420626081
      },
      "name":"Benedikt ",
      "function":"other"
   },
   "a677f826-4cb5-4cf0-ad17-a166ee290d4c":{
      "id":"a677f826-4cb5-4cf0-ad17-a166ee290d4c",
      "states":{
         "Luftfeuchtigkeit":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000445d0fa.humidity"
            },
            "unit":"%"
         },
         "Temp":{
            "state":{
               "node":"mihome.0.devices.sensor_ht_158d000445d0fa.temperature"
            },
            "unit":"°C"
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606420772708,
         "_updated":1606420821450
      },
      "name":"Keller",
      "function":"other"
   },
   "7d5910f5-54d3-4238-9c8b-2f50647d3523":{
      "id":"7d5910f5-54d3-4238-9c8b-2f50647d3523",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d00054cd378.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606520796726,
         "_updated":1606520949310
      },
      "name":"Türe",
      "function":"door"
   },
   "e55cef87-f943-4743-8cb4-01c369ae1e3d":{
      "id":"e55cef87-f943-4743-8cb4-01c369ae1e3d",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0004138051.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606520996961,
         "_updated":1606521018463
      },
      "name":"Küche",
      "function":"window"
   },
   "2f4f7b2b-73e7-42ad-8657-080c6316e469":{
      "id":"2f4f7b2b-73e7-42ad-8657-080c6316e469",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d000446c31e.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521065366,
         "_updated":1606521127722
      },
      "name":"Badezimmer",
      "function":"window"
   },
   "0060b38a-01b9-45c6-97a3-8fc605c106a0":{
      "id":"0060b38a-01b9-45c6-97a3-8fc605c106a0",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0003d5036d.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521168178,
         "_updated":1606521189367
      },
      "name":"Theresa",
      "function":"window"
   },
   "4a90190c-90a4-4b9b-9669-05fa71184efd":{
      "id":"4a90190c-90a4-4b9b-9669-05fa71184efd",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d00039cd409.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521224340,
         "_updated":1606521242215
      },
      "name":"Benedikt",
      "function":"window"
   },
   "73fd7ed4-b4bc-468f-af27-274d2b5904c7":{
      "id":"73fd7ed4-b4bc-468f-af27-274d2b5904c7",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0002e74522.state"
            }
         },
         "lock":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0002e74522.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521253741,
         "_updated":1606521305419
      },
      "name":"Terasse",
      "function":"door"
   },
   "60acd523-460d-43f4-944a-229f53f4c1ef":{
      "id":"60acd523-460d-43f4-944a-229f53f4c1ef",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0002e73c79.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521309335,
         "_updated":1606521358560
      },
      "name":"Wohnzimmer",
      "function":"window"
   },
   "d5333239-c25d-4779-8317-c3d11c620bcc":{
      "id":"d5333239-c25d-4779-8317-c3d11c620bcc",
      "states":{
         "open":{
            "state":{
               "node":"mihome.0.devices.magnet_158d0002e6bee9.state"
            }
         }
      },
      "options":{
         "hiddenStates":[
            
         ]
      },
      "attributes":{
         "_created":1606521388119,
         "_updated":1606521402850
      },
      "name":"WC",
      "function":"window"
   }
}
```

**Comment by Zefau** [comment]
Could you upgrade to the latest `v2.0.0-rc.1` ?

**Comment by Zefau** [comment]
I'm sorry to say, that due to the high number of responses I'm unable to support both v1.0.0 and v2.0.0 branch. This is why I would like to ask you to move forward to v2.0.0, since this is fixed in that branch.

**Comment by nicox** [comment]
Hi Zefau, Thank you for your reply. I did upgrade to 2.0.0-rc.1 
Bit i still have the same issue.
Please let me know if i am able to help or should try to help, jarvis is just perfect for me.

**Comment by Zefau** [comment]
Are you sure you are on v2.0.0-rc.1? Could you open the browser console (F12) and verify, if it states the correct version here as well?

![image](https://user-images.githubusercontent.com/14368811/100522750-8413f080-31ab-11eb-9a4e-5b330a79c818.png)

In case it states the correct version: Could you please provide your layout / widget config as well?

**Comment by nicox** [comment]
Hi Zefau, 
It states the wrong version.
I reinstalled the Instance and still 1.0.9.
I will check what else i can do and get back to you, thank you sooo much for your help.
Regards,
Nico

**Comment by Zefau** [comment]
Try and empty the cache.

**Comment by nicox** [comment]
I had to deinstall the Instance and the adpater and reinstall jarvis 2.0.0, after that it looks perfect!
