### ISSUE TITLE
Unit missing after using BlindLevelAction

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#50]
In `v1.0.0-beta-8` the unit is missing while/after using the BlindLevelAction.

![BlindLvelWidget](https://user-images.githubusercontent.com/2136249/92285633-12f2d300-ef05-11ea-8a84-a0fa19e7529a.gif)

**Comment by braindead1** [comment]
It's the default unit.

**Comment by Zefau** [comment]
Should be fixed with `v1.0.0-beta.10`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.10`

**Comment by braindead1** [comment]
In `v1.0.0-beta.13` the bug is back again. The unit is missing after using the BlindLevelAction.

**Comment by braindead1** [comment]
Directly after importing a blind alias device it has the following JSON. In this case the unit disappears.

    "bürorolladen_ecdb8": {
        "id": "bürorolladen_ecdb8",
        "name": "Büro Rolladen",
        "function": "blind",
        "states": {
          "level": {
            "state": "alias.0.Büro_Rolladen.SET",
            "action": "alias.0.Büro_Rolladen.SET"
          },
          "activity": {
            "state": "alias.0.Büro_Rolladen.WORKING",
            "action": "alias.0.Büro_Rolladen.STOP"
          },
          "SET": "alias.0.Büro_Rolladen.SET",
          "ACTUAL": "alias.0.Büro_Rolladen.ACTUAL",
          "STOP": "alias.0.Büro_Rolladen.STOP",
          "DIRECTION": "alias.0.Büro_Rolladen.DIRECTION",
          "WORKING": "alias.0.Büro_Rolladen.WORKING",
          "UNREACH": "alias.0.Büro_Rolladen.UNREACH"
        },
        "options": {},
        "attributes": {
          "manufacturer": {
            "name": "Alias Devices",
            "namespace": "alias"
          }
        },
        "imported": true
    }

After using the BlindLevelAction once the JSON is automatically changed into the following format. The unit still disappears.

    "bürorolladen_ecdb8": {
          "id": "bürorolladen_ecdb8",
          "name": "Büro Rolladen",
          "function": "blind",
          "states": {
             "level": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.SET"
                },
                "action": "alias.0.Büro_Rolladen.SET"
             },
             "activity": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.WORKING"
                },
                "action": "alias.0.Büro_Rolladen.STOP"
             },
             "SET": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.SET"
                }
             },
             "ACTUAL": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.ACTUAL"
                }
             },
             "STOP": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.STOP"
                }
             },
             "DIRECTION": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.DIRECTION"
                }
             },
             "WORKING": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.WORKING"
                }
             },
             "UNREACH": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.UNREACH"
                }
             }
          },
          "options": {
             "hiddenStates": []
          },
          "attributes": {
             "manufacturer": {
                "name": "Alias Devices",
                "namespace": "alias"
             }
          },
          "imported": true
    }

After removing the `SET` state, the unit does not disappear anoymore.

    "bürorolladen_ecdb8": {
          "id": "bürorolladen_ecdb8",
          "name": "Büro Rolladen",
          "function": "blind",
          "states": {
             "level": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.SET"
                },
                "action": "alias.0.Büro_Rolladen.SET"
             },
             "activity": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.WORKING"
                },
                "action": "alias.0.Büro_Rolladen.STOP"
             },
             "ACTUAL": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.ACTUAL"
                }
             },
             "STOP": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.STOP"
                }
             },
             "DIRECTION": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.DIRECTION"
                }
             },
             "WORKING": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.WORKING"
                }
             },
             "UNREACH": {
                "state": {
                   "node": "alias.0.Büro_Rolladen.UNREACH"
                }
             }
          },
          "options": {
             "hiddenStates": []
          },
          "attributes": {
             "manufacturer": {
                "name": "Alias Devices",
                "namespace": "alias"
             }
          },
          "imported": true
    }

After figuring out the above I checked if it's sufficient to remove the `SET` state directly after importing the blind alias device. It turns out, that the unit does not disappear anymore.

    "bürorolladen_ecdb8": {
        "id": "bürorolladen_ecdb8",
        "name": "Büro Rolladen",
        "function": "blind",
        "states": {
          "level": {
            "state": "alias.0.Büro_Rolladen.SET",
            "action": "alias.0.Büro_Rolladen.SET"
          },
          "activity": {
            "state": "alias.0.Büro_Rolladen.WORKING",
            "action": "alias.0.Büro_Rolladen.STOP"
          },
          "ACTUAL": "alias.0.Büro_Rolladen.ACTUAL",
          "STOP": "alias.0.Büro_Rolladen.STOP",
          "DIRECTION": "alias.0.Büro_Rolladen.DIRECTION",
          "WORKING": "alias.0.Büro_Rolladen.WORKING",
          "UNREACH": "alias.0.Büro_Rolladen.UNREACH"
        },
        "options": {},
        "attributes": {
          "manufacturer": {
            "name": "Alias Devices",
            "namespace": "alias"
          }
        },
        "imported": true
    }

**Comment by Zefau** [comment]
Thanks for your investigation! Very weird behavior. I will check the code; maybe `SET` is hardcoded somewhere or generally reserved.

**Comment by Zefau** [comment]
What state is `alias.0.Büro_Rolladen.SET` mapped to in your ioBroker configuration? 
I'm wondering if this bug is actually a bug within jarvis, because this is working fine for me. :-\

**Comment by braindead1** [comment]
The state `alias.0.Büro_Rolladen.SET` is mapped to `.1.LEVEL` of my HomeMatic blind.

**Comment by Zefau** [comment]
I guess that this object is writeable?
Could you share your layout definition for the "Erdgeschoss" widget as well?

For you transparency, what happens when you click the button:
1. level will be set to `100` within jarvis (no matter what the actual state is)
2. activity will be set to `true` (no matter what the actual state is)
3. command will be send to ioBroker to set state to `100`
4. updates from ioBroker will update the level / activity value


Thus, right after the click the value jumps to 100 (correctly), but immediately changes to 0 again (must be updated from the backend). When it changes to 0, the unit disappears, which means, that the update state is incorrect somehow.

I think I have to add some `console.log`'s and provide a debug-version to you for further details.

**Comment by Zefau** [comment]
@braindead1 Another try with `1.0.0-beta.24`. I refactored a little bit hoping this will solve this issue once and for all. If not, I will provide a debug version.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.25`
