### ISSUE TITLE
Expert mode not loading

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#63]
In `v1.0.0-beta.17` the expert mode is not loading. Instead the screen turn gray and the below erro messages are shon in the console.

![image](https://user-images.githubusercontent.com/2136249/92477636-3a85bc00-f1e1-11ea-8f02-72f13e12d8e7.png)

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.18`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.18`. 

I just noticed that the height of the dialogue shrinks when switching to expert mode and grows when switching back to normal mode. Is this the wanted behaviour?

**Comment by Zefau** [comment]
No. It is still not working correctly. Thanks for the feedback.

**Comment by Zefau** [comment]
Now it should be resolved with `1.0.0-beta.20`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.20`
